size(600,600);
background(0,0,200);
import javax.swing.JOptionPane;
String userInput;
userInput = JOptionPane.showInputDialog("Circle's Center x Coordinate: ");
int x = Integer.parseInt(userInput);
userInput = JOptionPane.showInputDialog("Circle's Center y Coordinate: ");
int y = Integer.parseInt(userInput);
userInput = JOptionPane.showInputDialog("Radius of Circle ");
int R = Integer.parseInt(userInput);
fill(255);
ellipse(x,y,R+R,R+R);
double radius = R;
double area = TWO_PI*R;
textSize(22);
fill(0);
text("Radius = " +radius,300,200);
text("Area = " +area,300,300);
line(x,y,x,y-R);
